[general]
project_name = "Calculadora Financiera BanBajio"
version = "0.1.0"
description = "Aplicación para realizar análisis, cálculos financieros y validaciones de cuentas y promociones bancarias."

[data]
# Rutas a los archivos de datos (para análisis manual, etc.)
cuentas_octubre = "data/CUENTAS_OCTUBRE.xlsx"
movimientos_octubre = "data/MOVIMIENTOS_OCTUBRE.xlsx"
promociones_octubre = "data/PROMOCIONES_OCTUBRE.xlsx"

[database]
# Configuración de la base de datos (estos valores pueden sobreescribirse con variables de entorno)
db_user = "app_admin"
db_password = "app_secure_password"
db_host = "localhost"
db_port = "5432"
db_name = "visa_db"

[streamlit]
# Opciones de configuración para Streamlit
page_title = "Calculadora Financiera BanBajio"
layout = "wide"
