version: 1
disable_existing_loggers: False
formatters:
  detailed:
    "()": "app.logging_formatter.MexicoCityFormatter"
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  simple:
    "()": "app.logging_formatter.MexicoCityFormatter"
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    level: INFO
  file:
    class: logging.FileHandler
    filename: app.log
    formatter: detailed
    level: INFO
loggers:
  app:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console, file]
